### PR TITLE
ci: build multi arch docker images using buildx

### PR DESCRIPTION
**Pull request by kskarthik**
- using buildx to also build docker image for arm64 platform
- ignore docker login in pull requests
- use official docker github action for dockerhub authentication

### CODE REVIEW

**Comment by kskarthik** [comment]
Although, the CI time is high now, caching will reduce the build times, once deployed

**Comment by mattwparas** [comment]
Sorry for the delay - did this try to publish while on a pull request?

**Comment by kskarthik** [comment]
@mattwparas no, it disables docker login on pull requests

**Comment by kskarthik** [comment]
@mattwparas did i answer your quetion ?

**Comment by mattwparas** [comment]
> @mattwparas did i answer your quetion ?

Sorry - yes you answered the question. Could we make it so that it doesn't try to push on the PR? It looks like the step for it is failing here.

**Comment by kskarthik** [comment]
> Sorry - yes you answered the question. Could we make it so that it doesn't try to push on the PR? It looks like the step for it is failing here.

@mattwparas done!

**Review by mattwparas — APPROVED** [review]

**Pull request merged**
