### PR TITLE
Build & Deploy docker image on each commit

### PR DESCRIPTION
**Pull request by kskarthik**
This github action builds the docker image from master branch on each commit & upload to docker hub

This is WIP as we did  not decide the docker hub username

### CODE REVIEW

**Comment by mattwparas** [comment]
> This github action builds the docker image from master branch on each commit & upload to docker hub
> 
> This is WIP as we did not decide the docker hub username

Thanks! Is there a docker hub alternative or is that the standard place to publish?

**Comment by kskarthik** [comment]
Github also has a container registry https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by mattwparas** [comment]
Got it - to start I can create a docker hub account, and then we can publish to github as well?

**Comment by kskarthik** [comment]
@mattwparas Yes, Let's continue with dockerhub first

**Comment by mattwparas** [comment]
Apologies for the delay - I need to create a docker hub account for steel explicitly; I think that makes more sense than publishing it under my own name

**Comment by kskarthik** [comment]
> Apologies for the delay - I need to create a docker hub account for steel explicitly; I think that makes more sense than publishing it under my own name

Yes, until first stable release. this is your username, correct? https://hub.docker.com/u/mattwparas

**Comment by kskarthik** [comment]
> Apologies for the delay - I need to create a docker hub account for steel explicitly; I think that makes more sense than publishing it under my own name

Yes, Please share the related dockerhub username

**Comment by mattwparas** [comment]
> > Apologies for the delay - I need to create a docker hub account for steel explicitly; I think that makes more sense than publishing it under my own name
> 
> Yes, Please share the related dockerhub username

Username is: `steelscheme` - I've added the docker hub password to the secrets

**Comment by kskarthik** [comment]
@mattwparas Ok, I have finished the refactoring. Just making sure that the secret name is `DOCKER_HUB_PWD` 

Then, It's ready to merge

**Comment by mattwparas** [comment]
> @mattwparas Ok, I have finished the refactoring. Just making sure that the secret name is `DOCKER_HUB_PWD`
> 
> Then, It's ready to merge

Yep, thats the secret name. Is it okay to just overwrite latest like that on each commit? I suppose since I haven't cut any specific tags it should be fine

**Comment by kskarthik** [comment]
There can be two options:

- We can use `latest` docker tag until you start tagging in git & later on docker `latest` tag only points to recent git tag.
- use the `master` tag which denotes the corresponding branch name in git 

Regarding the dockerhub behaviour, The current `latest` tag always gets overwritten. So you only have one `latest` image in the docker repo. the hash changes. The `docker pull steelscheme/steel:latest` will pull the latest hash of the image.

**Comment by mattwparas** [comment]
> There can be two options:
> 
> * We can use `latest` docker tag until you start tagging in git & later on docker `latest` tag only points to recent git tag.
> * use the `master` tag which denotes the corresponding branch name in git
> 
> Regarding the dockerhub behaviour, The current `latest` tag always gets overwritten. So you only have one `latest` image in the docker repo. the hash changes. The `docker pull steelscheme/steel:latest` will pull the latest hash of the image.

Cool, in that case I think for now I'll just have it tag latest and push there. When I start running some tags to cut real releases then we can update the publish step to actually have some real versions

**Review by mattwparas — APPROVED** [review]

**Pull request merged**
