### PR TITLE
Make steel-core compile for wasm32-unknown-unknown

### LINKED ISSUE #68: Update playground to use latest build
The playground is pretty out of date, and does not currently reflect the existing build.

### PR DESCRIPTION
**Pull request by mattwparas**
Adds the changes necessary for `steel-core` to compile to target `wasm32-unknown-unknown`

Helps to close #68 and #140

### CODE REVIEW

**Comment by gabydd** [comment]
should this have closed #140 instead of #68, or has the playground been updated as well?

**Comment by mattwparas** [comment]
Yes, it should have closed #140 - thanks. The playground has been updated, just tidying the code and will push momentarily

**Comment by gabydd** [comment]
awesome

**Comment by mattwparas** [comment]
New playground is live here -> https://mattwparas.github.io/steel-playground/dev/

**Pull request merged**
