### PR TITLE
Dockerfile: Build steel in release mode

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by kskarthik** [comment]
I am back again! 
Also, do u wish to setup a ci/cd for docker images? I am happy to help setting it up!

**Comment by mattwparas** [comment]
> I am back again! Also, do u wish to setup a ci/cd for docker images? I am happy to help setting it up!

That would be great! Do you want to do that as a separate PR? If so I can go ahead and get this merged

**Review by mattwparas — APPROVED** [review]

**Comment by kskarthik** [comment]
do you prefer publishing to dockerhub ?

**Comment by mattwparas** [comment]
> do you prefer publishing to dockerhub ?

I've never actually published anything! I see your MR though so I'll follow up there

**Pull request merged**
